# Generated by Django 3.0.2 on 2020-01-29 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveBooking',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=225, primary_key=True, serialize=False)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('number_of_rooms', models.IntegerField(default=1)),
                ('number_of_guest', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=225, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=225)),
                ('main_image', models.CharField(max_length=225)),
                ('available_rooms', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('addresss', models.CharField(max_length=225)),
                ('country', models.CharField(db_index=True, max_length=225)),
                ('number_of_bathrooms', models.IntegerField(default=1)),
                ('price', models.IntegerField(db_index=True, default=0)),
                ('discount', models.FloatField(max_length=225)),
                ('amenities', models.CharField(max_length=225)),
                ('rules', models.CharField(max_length=225)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=225, primary_key=True, serialize=False, unique=True)),
                ('category', models.CharField(default='Apartment', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=225, primary_key=True, serialize=False, unique=True)),
                ('review', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.Apartment')),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=225, primary_key=True, serialize=False, unique=True)),
                ('image', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.Apartment')),
            ],
        ),
        migrations.CreateModel(
            name='BookingArchive',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=225, primary_key=True, serialize=False)),
                ('was_completed', models.BooleanField(default=True)),
                ('was_canceled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.ActiveBooking')),
            ],
        ),
        migrations.AddField(
            model_name='apartment',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.Category'),
        ),
        migrations.AddField(
            model_name='activebooking',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.Apartment'),
        ),
        migrations.AddField(
            model_name='activebooking',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
