# Generated by Django 3.0.2 on 2020-01-12 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=uuid.uuid4, max_length=225, unique=True)),
                ('title', models.CharField(max_length=225)),
                ('main_image', models.ImageField(upload_to='')),
                ('available_rooms', models.IntegerField(default=1)),
                ('description', models.CharField(max_length=225)),
                ('type', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=225)),
                ('price', models.CharField(max_length=225)),
                ('discount', models.CharField(max_length=225)),
                ('amenities', models.CharField(max_length=225)),
                ('rules', models.CharField(max_length=225)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=225)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.Apartment')),
            ],
        ),
    ]
