# Generated by Django 3.0.2 on 2020-01-29 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='addresss',
            new_name='address',
        ),
    ]
