# Generated by Django 3.0.2 on 2020-03-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image10',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='images',
            name='image9',
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.CharField(max_length=225),
        ),
    ]
