# Generated by Django 3.0.2 on 2020-03-06 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_auto_20200306_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='other_images',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
