# Generated by Django 3.0.2 on 2020-02-01 08:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_auto_20200129_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=225, primary_key=True, serialize=False, unique=True)),
                ('amenity', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=225, primary_key=True, serialize=False, unique=True)),
                ('rule', models.CharField(max_length=225)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='apartment',
            name='amenities',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='rules',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=225, primary_key=True, serialize=False, unique=True)),
                ('rating', models.IntegerField(max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.Apartment')),
            ],
        ),
    ]
