# Generated by Django 3.0.2 on 2020-01-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_auto_20200124_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='number_of_bathrooms',
            field=models.IntegerField(default=1, max_length=10),
        ),
    ]
