# Generated by Django 3.0.2 on 2020-01-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_auto_20200112_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='available_rooms',
            field=models.FloatField(default=1),
        ),
    ]
