# Generated by Django 3.0.2 on 2020-01-27 09:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_apartment_number_of_bathrooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='uid',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='uid',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='uid',
            new_name='uuid',
        ),
        migrations.AddField(
            model_name='images',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=225, unique=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='number_of_bathrooms',
            field=models.IntegerField(default=1),
        ),
    ]
