# Generated by Django 3.0.2 on 2020-01-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_auto_20200112_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='available_rooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='discount',
            field=models.FloatField(max_length=225),
        ),
    ]
