# Generated by Django 3.0.2 on 2020-03-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_apartment_other_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='other_images',
        ),
        migrations.AlterField(
            model_name='apartment',
            name='check_in',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='check_out',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
