# Generated by Django 3.0.2 on 2020-02-01 08:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_auto_20200201_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='available_from',
            field=models.DateField(default=datetime.datetime(2020, 2, 1, 8, 32, 38, 964585, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='available_to',
            field=models.DateField(default=datetime.datetime(2020, 2, 1, 8, 32, 51, 345898, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apartment',
            name='check_in',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='check_out',
            field=models.TimeField(blank=True),
        ),
    ]
