# Generated by Django 3.0.2 on 2020-02-01 15:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_auto_20200201_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='activebooking',
            name='date_from',
            field=models.DateField(default=datetime.datetime(2020, 2, 1, 15, 59, 5, 803798, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activebooking',
            name='date_to',
            field=models.DateField(default=datetime.datetime(2020, 2, 1, 15, 59, 13, 723549, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
