# Generated by Django 3.0.2 on 2020-03-29 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0005_auto_20200306_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='apartment.Apartment'),
        ),
    ]
