# Generated by Django 3.0.2 on 2020-04-05 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0006_auto_20200405_1422'),
        ('apartment', '0006_auto_20200329_1016'),
    ]

    operations = [
    ]
