# Generated by Django 3.0.2 on 2020-02-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0006_auto_20200201_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='max_guest_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
