# Generated by Django 3.0.2 on 2020-02-01 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0007_apartment_max_guest_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='apartment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apartment.Apartment'),
        ),
    ]
