# Generated by Django 3.0.2 on 2020-04-07 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_userprofile_resident_city'),
        ('apartment', '0007_merge_20200405_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='given_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.UserProfile'),
        ),
    ]
