# Generated by Django 3.0.2 on 2020-05-30 17:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apartment', '0009_auto_20200530_1835'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActiveBooking',
            new_name='Booking',
        ),
        migrations.DeleteModel(
            name='BookingArchive',
        ),
    ]
