# Generated by Django 3.0.2 on 2020-02-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0009_auto_20200221_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(max_length=225, upload_to=''),
        ),
    ]
