# Generated by Django 3.0.2 on 2020-02-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0010_auto_20200221_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='image1',
            field=models.ImageField(default=1, max_length=225, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='image10',
            field=models.ImageField(default=1, max_length=225, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='image2',
            field=models.ImageField(default=1, max_length=225, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='image3',
            field=models.ImageField(default=1, max_length=225, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='image4',
            field=models.ImageField(default=1, max_length=225, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='image5',
            field=models.ImageField(default=1, max_length=225, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='image6',
            field=models.ImageField(default=1, max_length=225, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='image7',
            field=models.ImageField(default=1, max_length=225, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='image8',
            field=models.ImageField(default=1, max_length=225, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='images',
            name='image9',
            field=models.ImageField(default=1, max_length=225, upload_to=''),
            preserve_default=False,
        ),
    ]
