# Generated by Django 3.0.2 on 2020-03-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0011_auto_20200221_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apartment',
            old_name='available_from',
            new_name='unavailable_from',
        ),
        migrations.RenameField(
            model_name='apartment',
            old_name='available_to',
            new_name='unavailable_to',
        ),
        migrations.AddField(
            model_name='apartment',
            name='city',
            field=models.CharField(default='kigali', max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='extras',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='apartment',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='max_nights',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='min_nights',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='province',
            field=models.CharField(default='kigali', max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='space',
            field=models.CharField(default='private_room', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='total_rooms',
            field=models.IntegerField(default=1),
        ),
    ]
