# Generated by Django 3.0.2 on 2020-03-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0012_auto_20200305_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='main_image',
            field=models.CharField(max_length=225),
        ),
    ]
