# Generated by Django 3.0.2 on 2020-06-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0012_auto_20200621_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='extras',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
