# Generated by Django 3.0.2 on 2020-03-16 10:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartment', '0005_auto_20200306_1031'),
        ('authentication', '0006_pinverify'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=225, primary_key=True, serialize=False, unique=True)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.Apartment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.UserProfile')),
            ],
        ),
    ]
