# Generated by Django 3.0.2 on 2020-06-21 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=225, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=225)),
                ('date', models.DateField(blank=True)),
                ('start_time', models.TimeField(blank=True)),
                ('end_time', models.TimeField(blank=True)),
            ],
        ),
    ]
