# Generated by Django 3.0.2 on 2020-06-21 14:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20200621_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 6, 21, 14, 7, 24, 281535, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
