# Generated by Django 3.0.2 on 2020-06-21 14:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20200621_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default=datetime.datetime(2020, 6, 21, 14, 21, 1, 263982, tzinfo=utc), max_length=1),
            preserve_default=False,
        ),
    ]
