# Generated by Django 3.0.2 on 2020-01-08 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=225)),
                ('last_name', models.CharField(max_length=225)),
                ('address', models.CharField(blank=True, max_length=225)),
                ('resident_country', models.CharField(blank=True, max_length=225)),
                ('origin_country', models.CharField(blank=True, max_length=225)),
                ('phone', models.CharField(blank=True, max_length=225)),
                ('national_id', models.FileField(blank=True, upload_to='')),
                ('passport', models.FileField(blank=True, upload_to='')),
                ('is_host', models.BooleanField(blank=True)),
                ('is_admin', models.BooleanField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
