# Generated by Django 3.0.2 on 2020-03-05 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('address', models.CharField(blank=True, max_length=225)),
                ('resident_country', models.CharField(blank=True, max_length=225)),
                ('origin_country', models.CharField(blank=True, max_length=225)),
                ('phone', models.CharField(blank=True, max_length=225)),
                ('national_id', models.CharField(blank=True, max_length=225)),
                ('is_verified', models.BooleanField(blank=True, default=False)),
                ('passport', models.CharField(blank=True, max_length=225)),
                ('is_active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(blank=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
