# Generated by Django 3.0.2 on 2020-03-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.CharField(default='image_url', max_length=225),
            preserve_default=False,
        ),
    ]
