# Generated by Django 3.0.2 on 2020-01-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='national_id',
            field=models.CharField(blank=True, max_length=225),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='passport',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
