# Generated by Django 3.0.2 on 2020-01-27 08:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200127_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=100, unique=True),
        ),
    ]
