# Generated by Django 3.0.2 on 2020-04-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
