# Generated by Django 3.0.2 on 2020-04-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_passwordreset_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='resident_city',
            field=models.CharField(blank=True, max_length=225),
        ),
    ]
