# Generated by Django 3.0.2 on 2020-05-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_userprofile_resident_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='verification_status',
            field=models.CharField(default='U', max_length=1),
        ),
    ]
