# Generated by Django 3.0.2 on 2020-05-29 18:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_paymentmethod_momo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscribe',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(default='', max_length=225)),
            ],
        ),
    ]
